name: Build OpenWrt for JD BE6500

on:
  workflow_dispatch:  # 手动触发
  release:
    types: published  # 发布Release时触发

env:
  REPO_URL: https://github.com/openwrt/openwrt  # OpenWrt源码仓库
  REPO_BRANCH: master  # 主分支，可改为稳定版如v23.05.0
  FEEDS_CONF: feeds.conf.default  # 软件包源配置
  CONFIG_FILE: .config  # 编译配置文件
  DIY_P1_SH: diy-part1.sh  # 自定义脚本（更新feeds前执行）
  DIY_P2_SH: diy-part2.sh  # 自定义脚本（更新feeds后执行）
  UPLOAD_BIN_DIR: false  # 是否上传bin目录（包含所有编译文件）
  UPLOAD_FIRMWARE: true  # 是否上传固件
  UPLOAD_RELEASE: true  # 是否发布到Release
  TZ: Asia/Shanghai  # 时区设置

jobs:
  build:
    runs-on: ubuntu-22.04  # 运行环境

    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        path: scripts

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get -y install build-essential subversion git-core libncurses5-dev zlib1g-dev gawk flex quilt libssl-dev xsltproc libxml-parser-perl mercurial bzr ecj cvs unzip python3-distutils file wget
        sudo rm -rf /usr/share/dotnet /usr/local/lib/android/sdk

    - name: Clone OpenWrt source
      run: |
        git clone $REPO_URL -b $REPO_BRANCH openwrt
        cd openwrt
        echo "OPENWRT_PATH=$(pwd)" >> $GITHUB_ENV
    - name: International mirror priority feeds update
      run: |
        cd $OPENWRT_PATH
        
        # 定义镜像源列表（优先使用国外源）
        MIRRORS=(
          "https://downloads.openwrt.org"             # 官方源（首选）
          "https://mirrors.cloud.tencent.com/openwrt"  # 腾讯云镜像（国内，备用）
          "https://openwrt.cc"                        # 国内常用镜像（备用）
          "https://mirrors.tuna.tsinghua.edu.cn/openwrt"  # 清华大学镜像（备用）
          "https://mirrors.ustc.edu.cn/openwrt"      # 中科大镜像（备用）
        )
        
        # 检测最佳镜像（基于HTTP响应时间）
        echo "Testing mirrors for best performance..."
        BEST_MIRROR=""
        BEST_RESPONSE_TIME=9999
        
        for mirror in "${MIRRORS[@]}"; do
          echo "Testing $mirror..."
          response_time=$(curl -s -w "%{time_total}\n" -o /dev/null $mirror || echo "9999")
          response_time=${response_time%.*}  # 去除小数部分
          
          echo "  Response time: ${response_time}s"
          
          # 如果响应时间小于当前最佳时间，且HTTP状态码为200
          if [ $(echo "$response_time < $BEST_RESPONSE_TIME" | bc -l) -eq 1 ]; then
            http_code=$(curl -s -o /dev/null -w "%{http_code}" $mirror)
            if [ "$http_code" = "200" ]; then
              BEST_MIRROR=$mirror
              BEST_RESPONSE_TIME=$response_time
              echo "  ✅ This is the best mirror so far"
            fi
          fi
        done
        
        if [ -z "$BEST_MIRROR" ]; then
          echo "None of the mirrors are accessible. Using the first mirror as fallback."
          BEST_MIRROR=${MIRRORS[0]}
        fi
        
        echo "Selected best mirror: $BEST_MIRROR"
        
        # 获取当前分支名
        BRANCH=$(git branch --show-current || echo "$REPO_BRANCH")
        ARCH=qca-ipq807x/generic
        CPU_ARCH=aarch64_cortex-a53
        
        # 根据分支生成源URL
        if [[ $BRANCH == "master" || $BRANCH == "dev" ]]; then
          BASE_URL="$BEST_MIRROR/snapshots"
        else
          CLEAN_BRANCH=${BRANCH#v}
          BASE_URL="$BEST_MIRROR/releases/$CLEAN_BRANCH"
        fi
        
        # 写入新的feeds.conf.default
        cat > feeds.conf.default << EOF
        src-gz openwrt_core $BASE_URL/targets/$ARCH/packages
        src-gz openwrt_base $BASE_URL/packages/$CPU_ARCH/base
        src-gz openwrt_luci $BASE_URL/packages/$CPU_ARCH/luci
        src-gz openwrt_packages $BASE_URL/packages/$CPU_ARCH/packages
        src-gz openwrt_routing $BASE_URL/packages/$CPU_ARCH/routing
        src-gz openwrt_telephony $BASE_URL/packages/$CPU_ARCH/telephony
        EOF
        
        # 添加自定义软件包源（使用GitHub官方地址，而非Gitee）
        echo "src-git kenzo https://github.com/kenzok8/openwrt-packages.git" >> feeds.conf.default
        echo "src-git small https://github.com/kenzok8/small.git" >> feeds.conf.default
        
        # 打印生成的配置
        echo "Generated feeds.conf.default:"
        cat feeds.conf.default
        
        # 创建详细的日志文件
        LOG_FILE="feeds_update.log"
        touch $LOG_FILE
        
        # 清理旧的feeds缓存
        rm -rf feeds/*
        
        # 尝试更新feeds（增强版重试机制）
        echo "Updating feeds using $BEST_MIRROR..."
        UPDATE_SUCCESS=false
        
        for i in {1..5}; do  # 增加重试次数到5次
          echo "Attempt $i/5 to update feeds..."
          
          # 分步更新，提高成功率
          ./scripts/feeds update base packages luci 2>&1 | tee -a $LOG_FILE
          if [ $? -ne 0 ]; then
            echo "Step 1: Failed to update base packages"
            continue
          fi
          
          ./scripts/feeds update routing telephony 2>&1 | tee -a $LOG_FILE
          if [ $? -ne 0 ]; then
            echo "Step 2: Failed to update routing and telephony"
            continue
          fi
          
          ./scripts/feeds update kenzo small 2>&1 | tee -a $LOG_FILE
          if [ $? -ne 0 ]; then
            echo "Step 3: Failed to update custom feeds"
            # 尝试从Gitee获取（如果GitHub失败）
            echo "Fallback to Gitee for custom feeds..."
            sed -i 's|https://github.com/kenzok8|https://gitee.com/kenzok8|g' feeds.conf.default
            ./scripts/feeds update kenzo small 2>&1 | tee -a $LOG_FILE
            if [ $? -ne 0 ]; then
              echo "Failed to update custom feeds from both GitHub and Gitee"
              continue
            fi
          fi
          
          # 安装所有软件包
          echo "Installing all packages..."
          ./scripts/feeds install -a 2>&1 | tee -a $LOG_FILE
          if [ $? -eq 0 ]; then
            echo "✅ Feeds updated and installed successfully"
            UPDATE_SUCCESS=true
            break
          else
            echo "Failed to install packages, retrying..."
          fi
          
          # 清理不完整的更新
          rm -rf feeds/*
          sleep 15  # 增加等待时间到15秒
        done
        
        if [ "$UPDATE_SUCCESS" = "false" ]; then
          echo "Feeds update failed after 5 attempts!"
          echo "Full error log:"
          cat $LOG_FILE
          exit 1
        fi
        
        # 验证软件包数量
        PACKAGE_COUNT=$(./scripts/feeds list | grep -vE '^#|^$' | wc -l)
        echo "Total available packages: $PACKAGE_COUNT"
        
        if [ $PACKAGE_COUNT -lt 500 ]; then
          echo "Warning: Only $PACKAGE_COUNT packages found (expected >500)"
          echo "Listing available packages for debugging:"
          ./scripts/feeds list | grep -vE '^#|^$' | sort > available_packages.txt
          cat available_packages.txt
          exit 1
        else
          echo "Package installation verified successfully"
        fi
    - name: Customize feeds (Part 1)
      run: |
        if [ -f "$GITHUB_WORKSPACE/scripts/$DIY_P1_SH" ]; then
          cd $OPENWRT_PATH
          chmod +x $GITHUB_WORKSPACE/scripts/$DIY_P1_SH
          $GITHUB_WORKSPACE/scripts/$DIY_P1_SH
        else
          echo "No custom script $DIY_P1_SH found"
        fi

    - name: Load custom configuration
      run: |
        cd $OPENWRT_PATH
        if [ -f "$GITHUB_WORKSPACE/scripts/$CONFIG_FILE" ]; then
          cp $GITHUB_WORKSPACE/scripts/$CONFIG_FILE .config
        else
          echo "No custom config file found, using default"
          make defconfig
        fi

    - name: Customize configuration (Part 2)
      run: |
        if [ -f "$GITHUB_WORKSPACE/scripts/$DIY_P2_SH" ]; then
          cd $OPENWRT_PATH
          chmod +x $GITHUB_WORKSPACE/scripts/$DIY_P2_SH
          $GITHUB_WORKSPACE/scripts/$DIY_P2_SH
        else
          echo "No custom script $DIY_P2_SH found"
        fi

    - name: Download package dependencies
      run: |
        cd $OPENWRT_PATH
        make download -j$(nproc)
        find dl -size -1024c -exec ls -l {} \;
        find dl -size -1024c -exec rm -f {} \;

    - name: Build firmware
      run: |
        cd $OPENWRT_PATH
        echo -e "$(nproc) thread build"
        make -j$(nproc) V=s || make -j1 V=s  # 并行编译，失败则单线程重试

    - name: Check space usage
      run: |
        df -h
        du -sh $OPENWRT_PATH/bin

    - name: Collect firmware files
      id: collect
      run: |
        cd $OPENWRT_PATH/bin/targets/*/*
        FIRMWARE_PATH=$(pwd)
        echo "FIRMWARE_PATH=$FIRMWARE_PATH" >> $GITHUB_ENV
        echo "::set-output name=status::success"
        if [ -n "$(ls $FIRMWARE_PATH/*.bin 2>/dev/null)" ]; then
          echo "FILES_AVAILABLE=true" >> $GITHUB_ENV
        else
          echo "FILES_AVAILABLE=false" >> $GITHUB_ENV
        fi

    - name: Upload firmware as artifact
      if: steps.collect.outputs.status == 'success' && env.FILES_AVAILABLE == 'true' && env.UPLOAD_FIRMWARE == 'true'
      uses: actions/upload-artifact@v4
      with:
        name: OpenWrt-Firmware-${{ github.sha }}
        path: ${{ env.FIRMWARE_PATH }}
        retention-days: 30

    - name: Upload firmware to Release
      if: steps.collect.outputs.status == 'success' && env.FILES_AVAILABLE == 'true' && env.UPLOAD_RELEASE == 'true' && github.event_name == 'release'
      uses: softprops/action-gh-release@v1
      with:
        files: ${{ env.FIRMWARE_PATH }}/*
        tag_name: ${{ github.ref_name }}
        body: |
          OpenWrt firmware for JD BE6500
          Built from commit ${{ github.sha }}
          Date: $(date +%Y-%m-%d)
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}



