name: Get GitHub Runner Web Terminal

on:
  workflow_dispatch:
    inputs:
      timeout:
        description: '会话超时分钟数'
        default: '60'
        required: true

jobs:
  web-terminal:
    runs-on: ubuntu-22.04
    steps:
      # 第一步：手动安装 tmate（系统自带源，稳定无依赖）
      - name: Install tmate manually
        run: sudo apt update && sudo apt install -y tmate

      # 第二步：启动 tmate 并强制生成 Web 地址，同时打印到日志
      - name: Start tmate and show Web URL
        run: |
          # 启动 tmate 后台进程（避免阻塞）
          tmate -S /tmp/tmate.sock new-session -d
          
          # 等待 2 秒让 tmate 连接服务器（避免网络延迟导致地址没生成）
          sleep 2
          
          # 关键：用 tmate 自带命令直接获取 Web 地址和 SSH 命令
          echo "======================================"
          echo "✅ 网页终端地址（复制到浏览器）："
          tmate -S /tmp/tmate.sock display-message -p '#{tmate_web_url}'
          echo -e "\n✅ SSH 连接命令（终端运行）："
          tmate -S /tmp/tmate.sock display-message -p '#{tmate_ssh_command}'
          echo -e "\n⏰ 会话 ${INPUT_TIMEOUT} 分钟后自动关闭"
          echo "======================================"
          
          # 保持会话不退出（按超时时间等待）
          sleep $((INPUT_TIMEOUT * 600))
        env:
          INPUT_TIMEOUT: ${{ github.event.inputs.timeout }}
    
