name: SSH into GitHub Actions runner

on:
  workflow_dispatch:
    inputs:
      timeout:
        description: 'tmate session timeout in minutes'
        default: '600'
        required: true

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup tmate session (with Web URL output)
        uses: mxschmitt/action-tmate@v3
        with:
          timeout-minutes: ${{ github.event.inputs.timeout }}
          limit-access-to-actor: true
          # 关键：通过 `additional-ssh-args` 触发变量打印，或直接在同步骤运行命令
          # 以下命令会在 tmate 启动后，立即打印 Web 地址和 SSH 信息
          command: |
            echo "======================================"
            echo "✅ tmate 会话已启动！"
            echo "【网页连接】复制到浏览器打开：$TMATE_WEB_URL"
            echo "【SSH 连接】终端运行：ssh $TMATE_SSH_HOST"
            echo "【会话有效期】${{ github.event.inputs.timeout }} 分钟"
            echo "======================================"
          # 可选：启用 IPv6（解决部分网络无法访问网页的问题）
          # enable-ipv6: true
    
